### ISSUE TITLE
Has this script been tested with Ubuntu 23.04 Lunar Lobster?

### ISSUE THREAD

**Issue by olddesklamp** [popey/unsnap#53]
I'm hesitant to try it with my setup out of fear of breaking my system.

**Comment by MisterSheeple** [comment]
I'm running Kubuntu 23.04, so YMMV since we're not on the same distro, but I did notice that `gnome-42-2204` is not in the exclusions list as it should be, so I added it there (and also submitted a pull request so that this can be fixed for others too). Otherwise no breakage for me, but as I said YMMV since you're using regular Ubuntu.

If you want to check what snap packages you have installed, you can do so using these commands:

```
ls -l /snap/bin
ls -l /var/lib/snapd/snaps
```

**Comment by olddesklamp** [comment]
Tested and worked, although Firefox was kinda buggy so I have that reverted to a snap.
